### ISSUE TITLE
ST-Link V2 debugging stick

### ISSUE THREAD

**Issue by Zuldan** [povlhp/FlySkyRxFirmware#2]
Hi povlhp, thank you for all your hard work. Please could you kindly provide a link to the ST-Link V2 debugging stick on Banggood? There are so many to choose from and I can't find one that looks exactly like yours in the picture.

**Comment by povlhp** [comment]
Never found one on Banggood. But have bought a couple on eBay. Both China
and UK.

**Comment by Zuldan** [comment]
How about this one?

https://www.ebay.com.au/itm/HQ-ST-Link-V2-Programming-Unit-mini-STM32-STM8-Emulator-Downloader-M89-Useful/232553098713
